### ISSUE TITLE
Pass default touch events

### ISSUE THREAD

**Issue by dgavey** [runspired/ember-mobiletouch#5]
Since Hammer.js 2 does not have a drag api yet, I need access to the touchstart, touchend and touchmove events. I have added them manually to the hammer-events.js to let them pass through.  I understand that this can be a performance issue though.  I was wondering if there was a way with the current version to allow those events to pass through on a view by view basis like the gestureAllow works now.  If not maybe I could make a PR for it, if you can give me a heads up on how/if we can do that.

**Comment by runspired** [comment]
If you're willing to take the performance hit, the way to do this is to override the events in use in `config/environment.js`

```
ENV.mobileTouch.events = {
    touchstart : 'touchStart',
    touchend : 'touchEnd',
    touchmove : 'touchMove',
      keydown     : 'keyDown',
      keyup       : 'keyUp',
      keypress    : 'keyPress',
      contextmenu : 'contextMenu',
      mousemove   : 'mouseMove',
      focusin     : 'focusIn',
      focusout    : 'focusOut',
      mouseenter  : 'mouseEnter',
      mouseleave  : 'mouseLeave',
      submit      : 'submit',
      input       : 'input',
      change      : 'change',
      dragstart   : 'dragStart',
      drag        : 'drag',
      dragenter   : 'dragEnter',
      dragleave   : 'dragLeave',
      dragover    : 'dragOver',
      drop        : 'drop',
      dragend     : 'dragEnd'
}
```

**Comment by dgavey** [comment]
Perfect, seems to work ok for now, thanks.  Would love to be able to turn those on only on a specific view though.  I'll see about working on that later.

**Comment by runspired** [comment]
Thanks, I'll update the docs to reflect that you can do this, as well as to reflect `ENV.mobileTouch.use` which sets which high level gestures are expected (currently all by default, but you can turn stuff off for performance gains if you know you aren't using certain gestures).

Aside: I'd rather a PR for a well implemented solution for drag than one for sending through touchEvents.  The goal here is to be as performant as possible by design, with features that may cause performance bottlenecks available behind feature settings in config.

The most expensive events (by nature) are  "touchMove" "mouseMove" "mouseEnter" and "mouseLeave" because these trigger so often.  An upcoming minor release may remove "mouseMove" "mouseEnter" and "mouseLeave" as well, leaving it to users to add in their config if they know they want them.
